# Generated by Django 5.2.5 on 2025-09-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.IntegerField(unique=True)),
                ("capacity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Available"),
                            ("E", "Engaged"),
                            ("B", "Booked"),
                            ("U", "Under Maintanance"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "seating",
                    models.CharField(
                        choices=[
                            ("AC", "Air Conditioner Room"),
                            ("IN", "Indoor Non AC"),
                            ("OT", "Outdoor Seating"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("phone", models.IntegerField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("no_of_guests", models.IntegerField()),
                (
                    "alloted_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reservation.tables",
                    ),
                ),
            ],
        ),
    ]
