# Generated by Django 5.2.5 on 2025-08-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="updated_at",
        ),
    ]
