# Generated by Django 5.2.5 on 2025-08-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_remove_menuitem_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="item_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_category",
                to="menu.itemcategory",
            ),
        ),
    ]
